version: '3.7'
services:
  server:
    build:
      dockerfile: Dockerfile
    container_name: server
    hostname: server
    ports:
      - "8081:8081"
    depends_on:
      - db_resources
    env_file:
      - .env
    networks:
      - backend
    restart: always
  db_resources:
    image: postgres:14.1-alpine
    container_name: db_resources
    hostname: db_resources
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - backend
    restart: always
networks:
  backend:
    driver: 'bridge'
