version: '3.7'

services:
  api:
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    command: /bin/sh -c "alembic upgrade head && uvicorn app.server:app --host 0.0.0.0 --port 8000 --reload"
    container_name: api
    hostname: api
    ports:
      - '8000:8000'
    tty: true
    depends_on:
      - db
      - redis
    volumes:
      - $PWD:/var/www/
    env_file:
      - ../.env
    networks:
      - backend
    restart: always

  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: db
    hostname: db
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    networks:
      - backend
    restart: always

  redis:
    image: redis:6-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: 'bridge'

volumes:
  postgres_data:
